### ISSUE TITLE
`acc_match_mostfreq, acc_match_openend, acc_match_multiple` are nil

### ISSUE THREAD

**Issue by ili3p** [metalbubble/VQAbaseline#1]
Here https://github.com/metalbubble/VQAbaseline/blob/master/opensource_baseline.lua#L131
They are added to `stat`, but they are actually `nil`. 
Should modify https://github.com/metalbubble/VQAbaseline/blob/master/opensource_base.lua#L567 and define them there.

For example:  `acc_match_openend = perfs.openend_overall`

Error log:

```
/root/torch/install/bin/lua: opensource_baseline.lua:144: attempt to compare number with nil
stack traceback:
    opensource_baseline.lua:144: in function 'runTrainVal'
    opensource_baseline.lua:174: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: ?
```

**Comment by zhoubolei** [comment]
Thanks for pointing it out. The bug is fixed. Please let me know if there is other bug.
