### ISSUE TITLE
opensource_baseline.lua:130: attempt to concatenate global 'method' (a nil value)

### ISSUE THREAD

**Issue by SeekPoint** [metalbubble/VQAbaseline#6]
epoch 72/73     
train: acc (mostFreq) =0.59377712167544 
train: acc.match mostfreq = 0.59377712167544    
train: acc.dataset (OpenEnd) =0.65216301980117  
train: acc.dataset (MultipleChoice) =0.71316070992436   
train loss=121.30875051815      
saving model /home/rzai/prj/VQAbaseline/model/BOWIMG.t7 
epoch 73/73     
train: acc (mostFreq) =0.59476938633703 
train: acc.match mostfreq = 0.59476938633703    
train: acc.dataset (OpenEnd) =0.6531039138127   
train: acc.dataset (MultipleChoice) =0.71370415732758   
train loss=120.81262839181      
saving model /home/rzai/prj/VQAbaseline/model/BOWIMG.t7 
use GPU IDX=1   
Load question file = /home/rzai/prj/VQAbaseline/vqa_opensource/coco_test-dev2015_question.txt   
googlenetFCdense        
test: acc (mostFreq) =-1        
test loss=1588.2096077554       
/home/rzai/torch/install/bin/luajit: opensource_baseline.lua:130: attempt to concatenate global 'method' (a nil value)
stack traceback:
        opensource_baseline.lua:130: in function 'runTest'
        opensource_baseline.lua:144: in main chunk
        [C]: in function 'dofile'
        ...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
rzai@rzai00:~/prj/VQAbaseline$

**Comment by zhoubolei** [comment]
method -> opt.method
